// <auto-generated />
using System;
using LibraryService.Api.Infrastructure.Data.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryService.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260622142604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.AuthorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookEntityId");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.BookAuthorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorEntityId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BookId");

                    b.HasIndex("BookId1");

                    b.ToTable("BookAuthors", (string)null);
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.BookCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BookId1");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId1");

                    b.ToTable("BookCategories", (string)null);
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.BookPublisherEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublisherId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookEntityId");

                    b.HasIndex("BookId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("PublisherId1");

                    b.ToTable("BookPublishers", (string)null);
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookEntityId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.FineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LoanId")
                        .IsUnique();

                    b.ToTable("Fines", (string)null);
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.LoanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookEntityId");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberId1");

                    b.ToTable("Loans", (string)null);
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.MemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.PublisherEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers", (string)null);
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.ReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MemberEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookEntityId");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberEntityId");

                    b.HasIndex("MemberId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.AuthorEntity", b =>
                {
                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", null)
                        .WithMany("Authors")
                        .HasForeignKey("BookEntityId");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.BookAuthorEntity", b =>
                {
                    b.HasOne("LibraryService.Api.Domain.Entities.AuthorEntity", null)
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorEntityId");

                    b.HasOne("LibraryService.Api.Domain.Entities.AuthorEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", null)
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", "Book")
                        .WithMany()
                        .HasForeignKey("BookId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.BookCategoryEntity", b =>
                {
                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", null)
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", "Book")
                        .WithMany()
                        .HasForeignKey("BookId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryService.Api.Domain.Entities.CategoryEntity", null)
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryService.Api.Domain.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.BookPublisherEntity", b =>
                {
                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", null)
                        .WithMany("BookPublishers")
                        .HasForeignKey("BookEntityId");

                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryService.Api.Domain.Entities.PublisherEntity", null)
                        .WithMany("BookPublishers")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryService.Api.Domain.Entities.PublisherEntity", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.CategoryEntity", b =>
                {
                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", null)
                        .WithMany("Categories")
                        .HasForeignKey("BookEntityId");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.FineEntity", b =>
                {
                    b.HasOne("LibraryService.Api.Domain.Entities.LoanEntity", "Loan")
                        .WithOne("Fine")
                        .HasForeignKey("LibraryService.Api.Domain.Entities.FineEntity", "LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.LoanEntity", b =>
                {
                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", null)
                        .WithMany("Loans")
                        .HasForeignKey("BookEntityId");

                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryService.Api.Domain.Entities.MemberEntity", null)
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryService.Api.Domain.Entities.MemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.ReservationEntity", b =>
                {
                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", null)
                        .WithMany("Reservations")
                        .HasForeignKey("BookEntityId");

                    b.HasOne("LibraryService.Api.Domain.Entities.BookEntity", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryService.Api.Domain.Entities.MemberEntity", null)
                        .WithMany("Reservations")
                        .HasForeignKey("MemberEntityId");

                    b.HasOne("LibraryService.Api.Domain.Entities.MemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.AuthorEntity", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.BookEntity", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("BookAuthors");

                    b.Navigation("BookCategories");

                    b.Navigation("BookPublishers");

                    b.Navigation("Categories");

                    b.Navigation("Loans");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.CategoryEntity", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.LoanEntity", b =>
                {
                    b.Navigation("Fine");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.MemberEntity", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LibraryService.Api.Domain.Entities.PublisherEntity", b =>
                {
                    b.Navigation("BookPublishers");
                });
#pragma warning restore 612, 618
        }
    }
}
